title: rifat
title_path: /cv
url: "https://kakarotsec.github.io/cv"
baseurl: "/cv"

markdown: kramdown

tracking_id: 92611710
remote_theme: heartsker/resume@gem

footer: yes
footer_url: "https://github.com/kakarotsec/cv"
footer_text: "Made with ♥ on Earth, a minimalist Jekyll Theme by rifat"

sass:
    style: compressed
    sass_dir: _sass

# favicon_location: me.avif

nav:
 - name: "cv"
   link: "/cv/"
 - name: "pdf"
   link: "resume.pdf"
 - name: "contacts"
   link: "contacts"
